project:
  type: website
  output-dir: docs

website:
  title: "Shining"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: first_steps.qmd
        text: First steps
      - href: ui.qmd
        text: User interface

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

