---
title: "user interface"
---

The ui object in the default app is quite minimal, with a slider and a graph. The code looks more complex because it also includes functions to specify where in the app these two objects appear - the slider is in a sidebar and the graph is in the main panel of the window. There is also a title panel.

```         
# Define UI for application that draws a histogram
ui <- fluidPage(

    # Application title
    titlePanel("Old Faithful Geyser Data"),

    # Sidebar with a slider input for number of bins 
    sidebarLayout(
        sidebarPanel(
            sliderInput("bins",
                        "Number of bins:",
                        min = 1,
                        max = 50,
                        value = 30)
        ),

        # Show a plot of the generated distribution
        mainPanel(
           plotOutput("distPlot")
        )
    )
)
```

The slider is created by the **sliderInput()** and it is embedded within a **sidebarPanel()** that is part of the **sidebarLayout()**.

The parameters passed to the sliderInput() call define the name of the slider (*bins*), the text to be displayed in the ui (N*umber of bins:*), the minimum and maximum values (*1* to *50*) and the initial value (*30*). The name is not shown in the interface but is how the object will be referred to in the server code.

The graph is created by the **plotOutput()**, which is embedded within the **mainPanel()**. The graph that will be shown is called *distPlot*, and this will be created in the server code.

Both the sidebarLayout and the mainPanel are embedded within a **fluidpage()** call. A fluidpage is a layout that changes as the window is resized. If you have the app running, try making it narrower - when it gets too narrow, the sidebar will be moved above the main panel. There are many other ways of arranging the ui, and we'll look at some later, but a fluidpage is a good place to start.

## Input objects

The sliderInput() is just one of many different ways of providing user input to the app. Here is a list of other commonly used inputs:

-   actionButton() - a labelled button that will execute some code when clicked

-   checkboxInput() - a single checkbox you can use to turn something on or off

-   fileInput() - lets the user upload a data file

-   numericInput() - a dropdown where a number can be chosen (as for a slider)

-   radioButtons() - a visible set of mutually exclusive options (best for a small set)

-   selectInput() - a dropdown list of mutually exclusive options (best for a longer set)

-   textInput() - lets the user enter text

...and some less common inputs:

-   checkboxGroupInput() - a visible set of choices that are not mutually exclusive

-   dateInput() - specify a date by typing in the correct format e.g., dd-mm-yyyy

-   dateRangeInput() - two linked date inputs

-   passwordInput() - like textInput but blobs instead of letters shown

-   textAreaInput() - like textInput but with a stretchable box to type into

## Output objects
